"""add_detailed_metadata_fields_to_products

Revision ID: 2119d6102bff
Revises: 70a1b2c3d4e5
Create Date: 2025-12-19 13:11:00.352023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2119d6102bff'
down_revision: Union[str, None] = '70a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed drop operations for posts and invitations tables
    # as they may not exist in all database states
    op.add_column('products', sa.Column('official_website', sa.String(), nullable=True))
    op.add_column('products', sa.Column('license_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('products', sa.Column('detailed_description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('system_requirements', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('supported_formats', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('release_notes', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('release_date', sa.String(), nullable=True))
    op.add_column('products', sa.Column('crawled_from', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'last_crawled_at')
    op.drop_column('products', 'crawled_from')
    op.drop_column('products', 'release_date')
    op.drop_column('products', 'release_notes')
    op.drop_column('products', 'supported_formats')
    op.drop_column('products', 'system_requirements')
    op.drop_column('products', 'features')
    op.drop_column('products', 'detailed_description')
    op.drop_column('products', 'platform')
    op.drop_column('products', 'license_type')
    op.drop_column('products', 'official_website')
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_notice', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('views', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='posts_author_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    op.create_index('idx_posts_is_notice', 'posts', ['is_notice'], unique=False)
    op.create_index('idx_posts_created_at', 'posts', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_posts_category', 'posts', ['category'], unique=False)
    op.create_index('idx_posts_author_id', 'posts', ['author_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='invitations_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='invitations_pkey')
    )
    op.create_index('ix_invitations_id', 'invitations', ['id'], unique=False)
    op.create_index('ix_invitations_email', 'invitations', ['email'], unique=False)
    op.create_index('ix_invitations_code', 'invitations', ['code'], unique=False)
    # ### end Alembic commands ###
