"""add metadata_cache and unmatched_items tables

Revision ID: 42b8169e60a2
Revises: 9b393bc4b609
Create Date: 2026-01-03 18:30:17.843149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b8169e60a2'
down_revision: Union[str, None] = '9b393bc4b609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('software_name', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_cache_id'), 'metadata_cache', ['id'], unique=False)
    op.create_index(op.f('ix_metadata_cache_software_name'), 'metadata_cache', ['software_name'], unique=True)
    # Removed invitations table creation as it's already created in 70a1b2c3d4e5 migration
    op.create_table('unmatched_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('folder_path', sa.String(), nullable=False),
    sa.Column('parsed_name', sa.String(), nullable=True),
    sa.Column('parsed_version', sa.String(), nullable=True),
    sa.Column('parsed_vendor', sa.String(), nullable=True),
    sa.Column('suggested_metadata', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('manual_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_unmatched_items_id'), 'unmatched_items', ['id'], unique=False)
    op.create_index(op.f('ix_unmatched_items_status'), 'unmatched_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unmatched_items_status'), table_name='unmatched_items')
    op.drop_index(op.f('ix_unmatched_items_id'), table_name='unmatched_items')
    op.drop_table('unmatched_items')
    # Removed invitations table drop as it should be handled by 70a1b2c3d4e5 migration
    op.drop_index(op.f('ix_metadata_cache_software_name'), table_name='metadata_cache')
    op.drop_index(op.f('ix_metadata_cache_id'), table_name='metadata_cache')
    op.drop_table('metadata_cache')
    # ### end Alembic commands ###
