"""add_product_version_foreign_keys_to_filename_violations

Revision ID: 9045ed77eedd
Revises: ae474ffbf241
Create Date: 2025-12-30 15:29:56.721941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9045ed77eedd'
down_revision: Union[str, None] = 'ae474ffbf241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filename_violations', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('filename_violations', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_filename_violations_product_id'), 'filename_violations', ['product_id'], unique=False)
    op.create_index(op.f('ix_filename_violations_version_id'), 'filename_violations', ['version_id'], unique=False)
    op.create_foreign_key(None, 'filename_violations', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'filename_violations', 'versions', ['version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filename_violations', type_='foreignkey')
    op.drop_constraint(None, 'filename_violations', type_='foreignkey')
    op.drop_index(op.f('ix_filename_violations_version_id'), table_name='filename_violations')
    op.drop_index(op.f('ix_filename_violations_product_id'), table_name='filename_violations')
    op.drop_column('filename_violations', 'version_id')
    op.drop_column('filename_violations', 'product_id')
    # ### end Alembic commands ###
