"""Add is_portable to Version model

Revision ID: 9b393bc4b609
Revises: 838d2f66e4b9
Create Date: 2026-01-02 08:58:12.097114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b393bc4b609'
down_revision: Union[str, None] = '838d2f66e4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('is_portable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versions', 'is_portable')
    # ### end Alembic commands ###
