"""Add is_portable field to Product model

Revision ID: ae474ffbf241
Revises: af4ad8a75237
Create Date: 2025-12-30 15:17:34.826210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae474ffbf241'
down_revision: Union[str, None] = 'af4ad8a75237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_portable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_portable')
    # ### end Alembic commands ###
