"""add_installation_guide_to_products

Revision ID: b6b8b55b4309
Revises: f6a642543601
Create Date: 2025-12-23 10:57:51.333109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6b8b55b4309'
down_revision: Union[str, None] = 'f6a642543601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('installation_guide', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'installation_guide')
    # ### end Alembic commands ###
