"""Add filename_violations table

Revision ID: c1d2e3f4g5h6
Revises: abf6a8ec751c
Create Date: 2025-12-28 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d2e3f4g5h6'
down_revision: Union[str, None] = 'abf6a8ec751c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filename_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('violation_details', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filename_violations_id'), 'filename_violations', ['id'], unique=False)
    op.create_index(op.f('ix_filename_violations_folder_path'), 'filename_violations', ['folder_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filename_violations_folder_path'), table_name='filename_violations')
    op.drop_index(op.f('ix_filename_violations_id'), table_name='filename_violations')
    op.drop_table('filename_violations')
    # ### end Alembic commands ###
