"""add_file_metadata_to_attachments

Revision ID: d8507e4d8cd1
Revises: 42b8169e60a2
Create Date: 2026-01-03 19:11:03.538687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8507e4d8cd1'
down_revision: Union[str, None] = '42b8169e60a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_name', sa.String(), nullable=False))
    op.add_column('attachments', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('attachments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'created_at')
    op.drop_column('attachments', 'file_size')
    op.drop_column('attachments', 'file_name')
    # ### end Alembic commands ###
